### ISSUE TITLE
Nick Far asked to purge wiki history, possibly unrelated 11dec'15 tweet with commitment

### ISSUE THREAD

**Issue by o-jasper** [Enegnei/JacobAppelbaumLeavesTor#3]
I am glad i was wrong in feeling that waiting for the truth would "only dull the senses", as i felt it did with Ian Murdock.(Mind you i don't actually know these people, "only by software", but...) I tried taking notes, but nothing not noted here better already, really.

Nick Far was also asked to purge the history of the wiki page from the guy wanting to do a lightning talk on him being a US Intelligence Operative. Perhaps just distracting detail.(edit: alledgedly, of course)

11 Dec 2015,(creation of tweet ithink) Jake also [pinned](https://archive.is/UdNpw) `62f50063cf2f4be935275032e13394e4857c232b` However, no indication at all what it is about, or at all related. (perh. distracting detail..)

Note: i am in Eindhoven.

**Comment by Enegnei** [comment]
Thank you :) I've had people on "both" (I hate that this is already a binary thing) sides of the discussion sharing this repo, so I think that means I'm doing something right.

I don't know if they asked Nick to do the purging, he says "Jake also had _the CCC_ edit the 30c3 wiki database to eliminate any trace of the offending talk." I have no issues adding that detail though.

Yes, I was wondering what to do about that pinned tweet too. I haven't added it yet because like you, I don't know if it's related. He's tweeted different hashes before.
