### ISSUE TITLE
Relevant tweets (witnesses to another incident)

### ISSUE THREAD

**Issue by adrienne** [Enegnei/JacobAppelbaumLeavesTor#4]
https://twitter.com/micahflee/status/741727831672000512

(and the tweet it's quoting) are two witnesses to the account from "Phoenix" on the anon website

**Comment by adrienne** [comment]
...oh, n/m, I see that you saw them already! Sorry!

**Comment by Enegnei** [comment]
Yes, I haven't added Micah's yet because he hasn't answered and I want to be clear on what he is saying he witnessed/ heard. It's unclear whether he witnessed the incident with Phoenix or if he was confirming that he'd heard stories first-hand, or both. I'm leaning towards both but because this is about verifying stories I don't want to leave this kind of thing ambiguous.

**Comment by Enegnei** [comment]
I've found evidence to support that he did witness the incident, so even without him confirming my question about Phoenix's story, I'm considering it verified now.
